# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
