# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190917_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
