# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-20 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190919_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Products'),
        ),
    ]
